import { useState } from "react";
import { ChevronDown, ChevronUp } from "lucide-react";

const faqs = [
  {
    q: "How much does it cost to have a professional spray for roaches?",
    a: "Professional cockroach extermination in Clarksdale, MS typically costs between $100 and $400 per treatment depending on the severity of the infestation and the size of the property. A basic one-room spray for a minor infestation may start around $100, while whole-home treatments for a severe German roach infestation can run $300 to $600+. Many pest control companies offer bundled packages that include two or three service visits spaced 2 to 4 weeks apart, which provides much better value than multiple separate service calls. The technology used also affects cost — gel bait systems with insect growth regulators tend to deliver superior long-term results compared to basic residual sprays alone. Our Clarksdale specialists believe in transparent pricing with no surprise fees. Call (323) 880-1224 for a direct quote based on your specific property and infestation level. Investing in professional treatment early prevents costs from escalating as the roach population grows exponentially without intervention."
  },
  {
    q: "How do you get rid of 100% roaches?",
    a: "Achieving complete cockroach elimination requires a systematic approach targeting all life stages and every hiding spot simultaneously. Start by identifying and deploying gel bait in all known harborage areas — under appliances, inside cabinet hinges, behind electrical outlets, and within wall voids. Pair gel bait with a residual insecticide spray applied to baseboards, cracks, and crevices. Add an insect growth regulator (IGR) to sterilize eggs and prevent nymphs from maturing into reproducing adults — this is the cornerstone of breaking the reproductive cycle. Deep sanitation removes food and moisture sources that sustain the population. Professional exclusion work seals entry points such as pipe penetrations and gap-board joints. Follow-up treatments 21 days later address any surviving egg cases (oothecae) that have since hatched. In Clarksdale, MS's warm, humid climate, roaches can remain active year-round, making thorough initial treatment and follow-up visits essential. Our specialists deploy all these methods systematically. Call (323) 880-1224."
  },
  {
    q: "What's the worst pest to have in your house?",
    a: "Pest control professionals frequently debate which household pest is the 'worst,' but cockroaches and bed bugs consistently top the list for different reasons. Cockroaches are considered particularly dangerous because they carry and spread over 30 species of bacteria, including Salmonella, E. coli, and Staphylococcus. Their shed body parts, saliva, and fecal matter are potent allergens linked to asthma attacks, particularly in children. They contaminate food and surfaces constantly, are highly resistant to many insecticides, and reproduce at extraordinary speed — a single German roach female can produce over 30,000 offspring in a year. Bed bugs rank high for psychological toll — sleep deprivation and anxiety from infestations affect quality of life severely. Termites rank highest for sheer property damage. However, in a Mississippi home, cockroaches represent the most immediate public health threat in terms of disease transmission and allergen exposure. This is why fast, professional intervention matters so much. Call (323) 880-1224."
  },
  {
    q: "How do you get rid of a heavy roach infestation?",
    a: "A heavy cockroach infestation requires aggressive, multi-phase professional treatment — DIY products are almost never sufficient for moderate-to-severe cases. The first step is a thorough inspection to map all nesting sites, entry points, and high-activity zones. A professional then deploys multiple gel bait placements in dozens of harborage points simultaneously — far more application points than most homeowners attempt. A residual contact insecticide is applied to surfaces and voids where bait alone cannot be delivered. Insect growth regulators are applied to disrupt the reproductive cycle over the following weeks. For severe infestations, a void treatment using dust insecticides (such as boric acid or diatomaceous earth) inside wall cavities may be needed to reach inaccessible colonies. The property is sanitized by removing accessible food sources. A mandatory follow-up visit 14 to 21 days later targets the new generation hatching from surviving egg cases. For major infestations in Clarksdale, MS homes, our team may recommend a third visit. Call (323) 880-1224 now."
  },
  {
    q: "Is it worth getting an exterminator for roaches?",
    a: "Absolutely — for any cockroach infestation beyond an occasional sighting, professional extermination is almost always the most cost-effective and effective solution. The economics are clear: homeowners typically spend $50 to $150 on over-the-counter sprays, baits, and foggers over weeks or months without achieving full eradication, and eventually end up calling a professional anyway. Professional grade gel baits contain active ingredients at concentrations not available in consumer products, and professionals know exactly where and how to place them for maximum effectiveness. Cockroaches also develop resistance to insecticides rapidly — rotating product types (something professionals do routinely, consumers rarely do) is essential for sustained results. Beyond economics, the health cost is significant. Cockroach allergens are directly linked to asthma exacerbations, particularly in children. Every week of delayed treatment allows the population to grow exponentially — a problem of 20 roaches can become a problem of 2,000 within months. Call (323) 880-1224 for rapid service."
  },
  {
    q: "What attracts roaches to a house?",
    a: "Cockroaches are attracted to homes primarily by the presence of food, water, and shelter. Even a clean home can attract roaches if it offers moisture from leaking pipes, condensation under sinks, or standing water in drip trays. Food sources that attract roaches include exposed garbage, unwashed dishes, pet food left in open bowls, grease buildup around stoves and appliances, cardboard boxes with food residue, and even book binding glue. Warmth is another key attractor — roaches are cold-blooded and gravitate toward heat sources like electrical panels, water heaters, and warm appliances. In Clarksdale, MS, the warm and humid climate extends cockroach activity year-round and makes indoor environments especially hospitable. Structural entry points — gaps around pipes, unsealed cracks in foundations, and openings around utility lines — also attract roaches moving in from the outside or from neighboring units in multi-family housing. Addressing these attractors is part of a complete long-term treatment strategy that our team implements alongside extermination. Call (323) 880-1224."
  },
  {
    q: "How do you find a cockroach nest?",
    a: "Cockroach nests are not built like bird nests — they are harborage areas where large numbers of roaches congregate to shelter, reproduce, and share warmth and food proximity. Finding them requires systematic inspection of the most common locations: inside kitchen cabinets especially at the back corners and around hinges; beneath and behind all kitchen appliances including the refrigerator motor housing, stove drawer, microwave, and dishwasher; inside the motor compartment of the refrigerator; inside and behind electrical switch plates and outlet covers; within wall voids accessed through gaps around pipes; under sinks near plumbing connections; inside cardboard boxes or paper storage areas; and in basement and crawl space areas near heat sources. In a roach-infested home, evidence of a nest includes visible egg cases (small, brown, bean-shaped oothecae), dark smears of fecal matter, a musty sweet odor, and clusters of shed exoskeletons. Flushing harborage areas with a flashlight at night when roaches are most active is the most effective method of location. Our Clarksdale specialists identify all nesting areas during inspection."
  },
  {
    q: "Why shouldn't I squish a roach?",
    a: "Squishing a cockroach is not recommended for several important reasons. A gravid (pregnant) female cockroach may be carrying an ootheca — a hardened egg case containing 30 to 50 eggs on average. Squishing the roach can cause the ootheca to rupture and scatter eggs that may survive and hatch, potentially worsening your infestation. The impact of squishing does not reliably destroy cockroach eggs. Additionally, cockroach bodies release pheromones and bodily fluids when crushed that can actually attract other roaches to the same location and signal danger or food to nearby colony members. Cockroach body parts and frass (feces) left after squishing are potent allergens and can trigger asthma attacks and allergic reactions in sensitive household members. Finally, squishing individual roaches does nothing to address the underlying infestation — for every visible cockroach, estimates suggest there can be dozens or hundreds hidden in harborage areas. The only reliable solution is professional treatment targeting the entire population, not individual insects. Call (323) 880-1224."
  },
  {
    q: "Does one large cockroach mean infestation?",
    a: "Not necessarily — a single large cockroach, particularly an American cockroach or a smokey-brown cockroach, may be a lone wanderer that entered your Clarksdale home from outside through a gap in the foundation, a sewer pipe, or a door seal. These larger species are sometimes called 'occasional invaders' because they tend to live outdoors and enter homes opportunistically rather than establishing full indoor colonies. However, seeing an American cockroach indoors is always worth taking seriously because it can signal moisture problems or entry points that need sealing, and what begins as occasional outdoor species can become an established infestation if conditions inside are favorable. German cockroaches, by contrast, are exclusively indoor insects — seeing even a single German cockroach is a definitive indicator of an indoor infestation that requires immediate professional attention. German roaches reproduce far faster and are far harder to eliminate than their larger cousins. If you are unsure of the species, contact our Clarksdale team at (323) 880-1224 for an inspection and species identification — knowing what you are dealing with determines the correct treatment approach."
  },
  {
    q: "What's worse, rats or roaches?",
    a: "Both rats and cockroaches represent serious health threats and can cause significant property damage, but they pose different types and scales of risk. Rats are physically destructive — they chew through wiring (creating fire hazards), insulation, drywall, and food packaging. They transmit dangerous diseases including hantavirus, leptospirosis, rat-bite fever, and salmonellosis, and their presence represents a more obvious and alarming infestation. Cockroaches, by contrast, are harder to detect in early stages, reproduce much faster, and affect a greater number of homes. Their allergens — shed skin, saliva, and feces — are a leading trigger of asthma in urban children and are estimated to affect millions of Americans. Cockroaches also carry bacteria from sewage and garbage into kitchens, contaminating food preparation surfaces constantly. In terms of sheer number of homes affected and cumulative public health impact, cockroaches arguably represent the greater everyday threat. In Clarksdale, MS, both pests thrive in the warm, humid climate, and addressing either one promptly is essential. Call (323) 880-1224."
  },
  {
    q: "How to tell if your house is infested?",
    a: "Signs of a cockroach infestation in your Clarksdale home include: seeing live roaches during the day (since cockroaches are nocturnal, daytime sightings typically indicate a large established population with overcrowded harborage areas); a strong, musty, oily odor in kitchen and bathroom areas; small dark droppings resembling ground coffee or black pepper on surfaces, in drawers, and along baseboards; brown, purse-shaped egg cases (oothecae) found in corners, under appliances, or behind furniture; smear marks on surfaces near water sources where roaches travel; and shed exoskeleton casings in and around cabinet areas. Checking with a flashlight under the refrigerator, under the stove, inside cabinet corners, and behind the dishwasher at night can reveal nesting activity. Dead roaches found in corners or near baseboards also indicate active infestation. The more of these signs present, and the more widespread they are across multiple rooms, the more severe the infestation. Any combination of these signs warrants immediate professional inspection. Call our Clarksdale team at (323) 880-1224 for a thorough assessment."
  },
  {
    q: "What is the hardest bug to exterminate?",
    a: "Among all household insects, German cockroaches (Blattella germanica) are widely recognized as the most difficult pest to exterminate. Their extraordinary resistance to insecticides — built through decades of evolutionary pressure — means that the same products repeatedly applied without rotation become ineffective within a few generations. They reproduce at a staggering pace: females produce an ootheca every 3 to 4 weeks, each containing up to 48 eggs, meaning a single pair can produce hundreds of offspring in months. They hide in locations that are nearly impossible to treat with standard spray applications, including inside wall voids, behind refrigerator compressors, and within electrical components. Their small, flat body shape allows them to squeeze through gaps of less than 1.6mm. Oothecae (egg cases) are protected by a tough protein shell that is highly resistant to most chemical insecticides. Successfully eliminating German roaches requires professional-grade combination products, rotation of active ingredients, precision placement of multiple types of bait, and mandatory follow-up treatment. Our Clarksdale team is specifically trained to address German roach resistance. Call (323) 880-1224."
  },
  {
    q: "Which three signs should a manager notice for a cockroach infestation?",
    a: "For a property manager in Clarksdale, MS, the three most important early warning signs of a cockroach infestation in a managed property are: (1) Tenant complaints of nocturnal activity — if residents report seeing cockroaches moving around their kitchen or bathroom at night, particularly more than one sighting, this indicates an established population that has reached a density where harborage areas can no longer contain all individuals during daylight hours. (2) Visible fecal evidence — small dark droppings resembling coarse black pepper or coffee grounds on cabinet shelves, under sinks, in corners, or on counter surfaces are a highly reliable indicator of active cockroach presence and should be investigated immediately. (3) The characteristic musty, oily odor — a heavily cockroach-infested area develops a distinctive pungent smell from cockroach pheromones and body secretions that experienced property managers and pest control professionals recognize on sight. Catching an infestation at the first sign prevents cost escalation, liability exposure, and violation of health codes. Addressing the issue immediately protects tenants and the property's value. Call (323) 880-1224."
  },
  {
    q: "When you kill a cockroach vs killing a butterfly?",
    a: "This is an interesting ecological and ethical question. Killing a cockroach has no meaningful ecological consequence — cockroach populations replenish extremely quickly and no native ecosystem in Mississippi is dependent on any urban-dwelling cockroach species for any essential ecological function. By contrast, butterflies are important pollinators and a critical part of food webs; many bird, bat, and insect species depend on butterflies and their caterpillars as a food source. Butterfly populations in North America have decline significantly due to habitat loss, pesticide use, and climate change, and individual butterflies matter ecologically in ways that individual city cockroaches do not. From a public health perspective, cockroaches inside homes are disease vectors and allergen sources — their presence poses documented risks to human health, particularly for children with asthma. Butterflies pose no comparable risk. From a pest control standpoint, choosing targeted treatments that minimize impact on beneficial insects (like pollinators outdoors) while effectively eliminating indoor cockroach populations reflects responsible pest management. Our Clarksdale team uses EPA-registered precision gel baits that minimize outdoor chemical exposure. Call (323) 880-1224."
  },
  {
    q: "Do roaches only come out at night?",
    a: "Cockroaches are primarily nocturnal — they are most active during the nighttime hours and spend the day hiding in dark, warm, humid harborage areas. However, seeing cockroaches during daylight hours is not unusual and is actually a significant warning sign. When a population becomes overcrowded in its harborage areas, the excess individuals are forced out into the open even during daylight because there is not enough hidden space to shelter everyone. This means that daytime cockroach sightings frequently indicate a larger, more established infestation than would be suggested by nighttime sightings alone. Some individuals may also be displaced by treatment efforts — either professional or DIY — that disturb harborage areas and drive roaches into the open. In Clarksdale, MS's warm climate, cockroaches remain metabolically active year-round with no seasonal dormancy, meaning they can be seen at any time of day or night with equal frequency during severe infestations. If you are regularly seeing roaches during daylight in your home, the population is likely significantly larger than you realize. Call (323) 880-1224 for an immediate professional inspection."
  },
  {
    q: "What will make a roach come out of hiding?",
    a: "Several factors can draw cockroaches out of their harborage areas: darkness, since roaches emerge more readily when lights are off and activity is minimal; warmth, since their metabolism and movement increases with temperature and they move toward heat sources; moisture, especially near leaking pipes, condensation, or standing water; food odors from cooking, open garbage, or accessible pet food; and pheromones released by other roaches who have found a food source, which recruit nestmates to feed. Turning off all lights and returning to the kitchen after 30 minutes is a simple method of gauging cockroach activity level — use a flashlight to quickly scan under appliances, inside cabinets, and along baseboards. Placing sticky monitoring traps in high-activity areas and checking them after 24 to 48 hours is a reliable indicator of infestation severity and population distribution. Gel bait exploits cockroaches' food-driven emergence by presenting a highly attractive food matrix that draws roaches from harborage areas to consume the bait and return to the colony, transferring bait to nestmates. Call (323) 880-1224."
  },
  {
    q: "How to tell how bad a cockroach infestation is?",
    a: "The severity of a cockroach infestation in your Clarksdale home can be estimated by several key indicators. A minor infestation typically involves seeing only 1 to 5 roaches at night in specific areas like under the sink or behind the stove, with limited fecal evidence. A moderate infestation involves regular nighttime sightings in multiple rooms, obvious fecal spotting on surfaces and inside cabinets, a noticeable musty odor, and possibly finding egg cases. A severe infestation is indicated by daytime roach sightings (which suggest the harborage is overcrowded), roaches visible in multiple rooms including bedrooms and living areas, heavy fecal deposits, abundant egg cases, dead roaches found regularly, and a strong pervasive odor throughout the property. Placing sticky traps in high-activity areas overnight and counting captures within 24 hours can also quantify severity: catching 0-5 per trap suggests mild activity; 10-25 suggests moderate; over 25 suggests heavy infestation. Regardless of severity, any active roach infestation warrants professional treatment — the question of severity affects the number of visits and the specific treatment protocol. Call (323) 880-1224."
  },
  {
    q: "Where do roaches lay eggs in the house?",
    a: "Cockroaches lay their eggs inside hardened egg cases called oothecae, which they deposit in protected, dark, and humid locations close to food and water sources. The most common ootheca deposition sites in a Clarksdale home include: inside cabinet hinges and the dark rear corners of kitchen cabinets; underneath and behind major appliances including refrigerators (particularly near the motor), stoves, dishwashers, and microwaves; inside wall voids accessed through gaps around plumbing penetrations; behind loose or peeling wallpaper; inside cardboard boxes used for storage, especially in kitchens or pantries; within cracks in wooden furniture joints; and under bathroom sinks near moisture. German cockroaches carry their egg case attached to their body until just before hatching, making them harder to find before the eggs hatch, while American cockroaches deposit their oothecae shortly after forming them. Each ootheca can contain 14 to 48 eggs depending on the species, and a single female can produce multiple oothecae throughout her lifespan. Understanding ootheca placement is why chemical treatment alone is never sufficient — IGRs that prevent hatching are a crucial part of professional roach treatment."
  },
  {
    q: "What is roaches' biggest weakness?",
    a: "Cockroaches have several key vulnerabilities that effective pest control exploits. Their biggest weakness from a practical elimination standpoint is their feeding behavior — cockroaches are attracted to highly palatable food matrices, which makes gel bait an extraordinarily effective tool. Modern gel baits contain attractants and feeding stimulants that cockroaches find irresistible, and the active insecticide within the bait is transferred from feeding individual to nestmates through contact and through consumption of feces (cockroaches are coprophagic, meaning they consume their own excrement), resulting in what professionals call 'bait cascade' or 'secondary kill' that eliminates far more individuals than the number that directly consume the bait. Another key weakness is their reproductive biology — insect growth regulators interrupt the hormonal development pathway that allows nymphs to mature into reproducing adults, permanently sterilizing the next generation. Cockroaches are also highly sensitive to desiccation — diatomaceous earth and boric acid exploit this by abrading and absorbing the waxy cuticle that retains moisture in the insect's body, causing death by dehydration. Our Clarksdale team combines all these approaches."
  },
  {
    q: "What happens if you flush a cockroach down the toilet?",
    a: "Flushing a cockroach down the toilet will kill it in virtually all circumstances — cockroaches cannot swim indefinitely and will eventually drown in the water trap or be carried through the sewer system. While cockroaches are remarkable survivors and can hold their breath for extended periods (up to 40 minutes by some research estimates), the combination of drowning, mechanical trauma from water flow, and the hostile chemical environment of sewer systems means survival is extremely unlikely. It is important to note, however, that flushing individual roaches addresses nothing about the core infestation problem. Cockroaches can enter homes through floor drain traps, toilet water seals, and sewer line connections if water in trap seals evaporates or seals are broken — meaning your toilet and drains can actually be a point of entry for American cockroaches and Oriental cockroaches that live in sewer systems. Pouring water down infrequently used drains to maintain water traps in P-traps helps prevent sewer-connected roaches from entering. But for an active infestation in your Clarksdale home, the solution is professional treatment, not individual disposal. Call (323) 880-1224 immediately for a professional assessment."
  },
  {
    q: "What 100% gets rid of roaches?",
    a: "No single product achieves 100% roach eradication on its own — effective complete elimination requires a coordinated multi-product, multi-visit approach. The combination that professional pest controllers in Clarksdale deploy for maximum effectiveness includes: (1) Precision gel bait placement in all harborage areas — the gel draws roaches out and delivers secondary kill through the colony; (2) Residual contact insecticide spray on surfaces, baseboards, and voids to kill roaches that contact treated areas; (3) Insect growth regulator (IGR) application to prevent any surviving eggs and nymphs from maturing into reproducing adults; (4) Void and crack-and-crevice treatment using dust formulations in wall voids where spray cannot penetrate; (5) Deep sanitation and removal of food and moisture attractants; (6) Physical exclusion — sealing entry points to prevent reinfestation; and (7) A mandatory follow-up treatment 14 to 21 days after the initial visit to address newly hatched nymphs from surviving oothecae. When all these elements are deployed together by a licensed professional in the right quantities and locations, near-100% eradication is achievable within 4 to 6 weeks. Call (323) 880-1224."
  },
  {
    q: "How to tell if your furniture has roaches?",
    a: "Cockroaches frequently nest in furniture, particularly in dark crevices within wooden joints, upholstered seams, inside drawers, and behind detachable furniture backs. To determine if your furniture is harboring cockroaches, examine these areas carefully: pull out all drawers and inspect the inside corners, particularly where the bottom of the drawer meets the side panels — these are preferred harborage zones for German roaches. Look for small dark streaks or clusters of pepper-like droppings along furniture joints and drawer tracks. Check the undersides of upholstered furniture — flip cushions and inspect the fabric seams and any crevices in the frame structure. Wooden furniture joints, particularly in older pieces with loose or damaged finish, should be inspected with a flashlight for roach feces and egg cases. A tell-tale sweet, musty odor emanating from a specific piece of furniture is a strong indicator of roach activity within it. Placing sticky monitoring traps directly adjacent to or under suspected furniture overnight and checking in the morning will provide definitive evidence. If roaches are confirmed in furniture, the piece may need treatment or replacement as part of a comprehensive elimination plan. Call (323) 880-1224."
  },
  {
    q: "What is the most toxic thing in your house?",
    a: "From a pest control perspective, the question of toxicity in the home is important for context. Many homeowners express concern about pesticide exposure, but it's worth noting that household chemicals used daily — cleaning products, drain uncloggers, certain paints, carbon monoxide from gas appliances, and mold spores — often represent equivalent or greater health risks than properly applied, EPA-registered pest control products. In the context of cockroaches specifically, the insects themselves introduce a significant toxic burden to the home: they carry over 30 bacterial pathogens on their bodies and legs, deposit fecal matter containing these pathogens on food-preparation surfaces continuously, and shed exoskeletons that contain powerful allergens directly linked to childhood asthma. Research has shown that cockroach allergen levels in infested urban homes correlate directly with emergency room visits for asthma complications. Modern gel bait insecticides used by professional pest control services are applied in tiny quantities in targeted locations and are low-toxicity to mammals when used correctly. The ongoing health risk of a cockroach infestation far exceeds the residual risk of professionally applied insecticides. Call (323) 880-1224 for safe, effective treatment."
  },
  {
    q: "How fast do cockroaches multiply?",
    a: "Cockroaches multiply with alarming speed — particularly the German cockroach, which has the fastest reproductive rate of any common household cockroach species in North America. A single German cockroach female produces a new ootheca approximately every 3 to 4 weeks, and each ootheca contains 30 to 48 eggs. Under optimal conditions (warmth, humidity, and food access — conditions easily met in a Mississippi kitchen), German cockroach eggs hatch within 28 days, and newly hatched nymphs reach sexual maturity within 36 to 60 days. This means a single pregnant female can theoretically produce several hundred descendants within a few months. A realistic population growth estimate suggests that a starting population of 10 German cockroaches can grow to hundreds within 3 months and potentially thousands within 6 months if left untreated. American cockroaches reproduce more slowly — oothecae hatch in about 6 to 8 weeks, and development to adulthood takes 6 to 12 months — but they still establish large persistent colonies that require professional elimination. Clarksdale, MS's warm climate accelerates this reproductive cycle year-round. Call (323) 880-1224 immediately — delay always makes the problem larger."
  },
  {
    q: "What month do roaches come out?",
    a: "In Clarksdale, MS and throughout Mississippi, cockroaches are active year-round because the climate never gets cold enough to drive them into dormancy. Unlike northern states where winter temperatures suppress cockroach activity, Mississippi's temperate winters mean that indoor cockroach populations continue to breed and feed throughout every month of the year. That said, population levels do fluctuate with seasons. Summer months — June through September — see peak cockroach activity both indoors and outdoors due to the combination of high temperatures and elevated humidity that accelerates their metabolism and reproductive rate. American cockroaches and smokey-brown cockroaches tend to invade homes more aggressively in late summer and early fall as outdoor temperatures begin to drop, seeking warmth inside. German roaches, which are exclusively indoor pests, show less seasonal variation but may be noticed more during summer when home occupants host gatherings and food preparation activity increases. For Clarksdale residents, there is essentially no 'safe' month — professional preventive treatments and exclusion work are recommended year-round. Call (323) 880-1224 for a seasonal treatment plan."
  },
  {
    q: "Where do cockroaches hide in bedrooms?",
    a: "While cockroaches prefer kitchens and bathrooms, they are fully capable of establishing harborage in bedrooms — particularly in severe infestations where kitchen and bathroom areas can no longer support the entire population. In bedrooms, cockroaches most commonly hide in the following locations: inside and behind headboards, particularly those mounted close to walls; inside dresser and nightstand drawers, especially in the dark rear corners near the drawer track; behind or inside electronic devices like alarm clocks, gaming consoles, and televisions, which emit attractive warmth; inside closets near baseboards and at the floor level where clothing is stored; under the bed frame itself, particularly near the floor; within any cardboard boxes used for storage; along baseboards and behind loose baseboard molding; and inside any cracks in the walls or gaps around electrical outlets and switch plates. Bedroom cockroach activity often indicates a severe and spreading infestation that has exceeded the capacity of kitchen harborage zones, meaning the overall population in the home is likely very large. Finding roaches in a bedroom should trigger immediate professional treatment. Call (323) 880-1224 for same-day assessment."
  },
  {
    q: "Is seeing one roach a day bad?",
    a: "Seeing one cockroach per day is a meaningful warning sign that should not be dismissed — it indicates an active infestation of at least some scale. Research and pest control field experience consistently shows that for every cockroach seen, there are many more hiding that you never see. The commonly cited estimate is that visible cockroaches represent roughly 1 to 2% of the total population for German cockroaches, meaning seeing one per day could suggest a colony of dozens to hundreds in the harborage areas. While a single daily sighting does not necessarily indicate a catastrophic infestation, it is far from a trivial problem. The key factors to consider are the time of day (daytime sightings are more alarming than nighttime ones), the location (kitchen or bathroom sightings suggest a nearby colony; bedroom or living room sightings suggest spread), and the species. A single large American cockroach occasionally could be an outdoor wanderer; a single small German cockroach per day is a near-certain indicator of an established indoor colony. In any case, placing monitoring sticky traps and contacting a pest control professional in Clarksdale is the appropriate response. Call (323) 880-1224 before the population grows further."
  },
  {
    q: "Why shouldn't you kill roaches?",
    a: "There are several practical arguments against killing roaches by hand (squishing, swatting, etc.) as a primary control method. First, as noted in entomological research, squishing a gravid female cockroach may rupture or scatter her ootheca, potentially releasing eggs that survive and hatch. Second, crushed cockroach bodies release pheromones that can attract additional roaches to the same area and alert nearby colony members, potentially scattering the population to new areas rather than concentrating them where bait can be most effective. Third, and most practically significant: killing individual roaches does absolutely nothing to address the underlying population. For every visible roach killed by hand, dozens or hundreds remain hidden and protected in harborage areas, continuing to reproduce. Physical killing is the least efficient approach from a pest management standpoint — it provides a false sense of progress while the actual infestation continues unchecked. The most effective consumer strategy while awaiting professional treatment is to keep food stored in sealed containers, eliminate water sources, and not disturb harborage areas unnecessarily. Contact our Clarksdale specialists at (323) 880-1224 for immediate professional treatment."
  },
  {
    q: "What animal kills the most cockroaches?",
    a: "In natural ecosystems, several predatory animals are significant cockroach killers. Among insects, the Emerald jewel wasp (Ampulex compressa) is perhaps the most specialized cockroach predator — it paralyzes cockroaches with a precise venom injection and uses them as a live food source for its larvae. Spiders, centipedes, and ground beetles are common opportunistic cockroach predators in outdoor environments. Among vertebrates, many lizard species are voracious cockroach hunters — the house gecko, found throughout Mississippi and the southeastern United States, is an efficient nighttime predator that actively hunts cockroaches in walls and around homes. Certain species of frogs and toads also consume large quantities of cockroaches where outdoor populations exist. Among birds, chickens and many ground-feeding species will consume cockroaches opportunistically. However, it is extremely important to understand that no biological predator provides reliable control of indoor cockroach infestations — the controlled indoor environment, lack of predators, and the sheer reproductive rate of cockroaches means that populations quickly exceed what any natural predator can control. Professional extermination is the only reliable solution for household infestations. Call (323) 880-1224."
  },
  {
    q: "Will stomping on a roach kill it?",
    a: "Stomping on a cockroach is generally sufficient to kill it — despite their reputation for toughness, crushing force large enough to rupture the cockroach's exoskeleton is lethal. The durability myths about cockroaches surviving nuclear radiation and immense physical impacts are exaggerated popular lore. While cockroaches can withstand approximately 300 times their own body weight in pressure before their exoskeleton fails, a human foot delivers crushing force orders of magnitude greater than this threshold for a small insect. However, as mentioned, there are practical reasons to avoid this as a control strategy. A cockroach carrying an ootheca may have it crushed with the body — or the ootheca may be dislodged and survive. The crushed body is also a messy, allergen-laden cleanup problem, and the pheromones released can actually attract other roaches. From a practical standpoint, killing individual visible roaches by stomping has zero impact on the total population in your Clarksdale home and contributes nothing to resolving the underlying infestation. If you are seeing enough roaches to be regularly stomping on them, this is a clear sign that professional extermination treatment is urgently needed. Call (323) 880-1224 for same-day service."
  },
  {
    q: "What is the hardest bug infestation to get rid of?",
    a: "Among all household insects, the German cockroach infestation is consistently ranked by pest management professionals as the most difficult to fully eliminate. This ranking is due to a convergence of biological advantages that German roaches possess: extraordinary reproductive speed that outpaces most treatment timelines; highly developed insecticide resistance across multiple chemical classes developed through decades of exposure; the ability to survive on minimal food and water that no sanitation program can fully eliminate; a flat body profile that allows entry into cracks as thin as a dime; harborage in wall voids and appliance interiors that are physically inaccessible to many treatment methods; and protective egg cases that are chemically resistant to most contact insecticides. Bed bug infestations are a close second due to their own insecticide resistance, cryptic harboring behavior, and requirement for multiple treatment visits. Compared to either of these, most other household pest infestations — including mice, ants, and most fly species — are more straightforwardly treatable. For German cockroach infestations in Clarksdale, MS homes, our team deploys the specific combination of products and timing required to overcome all of these biological advantages. Call (323) 880-1224 for immediate professional assessment."
  },
  {
    q: "How many roaches indicate a problem?",
    a: "Any confirmed cockroach presence inside a home indicates a pest problem requiring immediate action — there is no 'safe' number of cockroaches to have indoors. That said, the severity level can be gauged by population indicators. Pest management professionals typically categorize cockroach infestations as follows: Light infestation — fewer than 5 cockroaches observed per monitoring trap per night, or occasional sightings limited to one area of the home, with minimal fecal evidence. Moderate infestation — 5 to 25 roaches captured per trap per night, regular nighttime sightings in kitchen and bathrooms, obvious fecal spotting, and egg cases present. Heavy infestation — more than 25 roaches per trap per night, daytime sightings across multiple rooms, pervasive fecal deposits on surfaces and in drawers, strong musty odor, and abundant egg cases visible. Any level requires professional treatment, but heavy infestations require more aggressive multi-product protocols and multiple service visits to achieve full eradication. In Clarksdale's climate, infestations classified as 'light' today can become 'heavy' within 60 to 90 days without intervention. Early treatment is always less expensive and less extensive than delayed treatment. Call (323) 880-1224 immediately."
  },
  {
    q: "Are American roaches hard to get rid of?",
    a: "American cockroaches (Periplaneta americana) are significantly easier to control than German cockroaches and with the right treatment, infestations are typically resolved in one to three professional service visits. Unlike German roaches, American cockroaches are primarily outdoor insects that occasionally invade interior spaces — their typical entry points are floor drains, sewer lines, basement wall cracks, and gaps around utility pipes. They do establish harborage indoors in basements, crawl spaces, and areas near floor drains or sump pits, particularly in Clarksdale, MS's humid climate. Control strategies for American cockroaches include: treating all entry points with residual insecticide; applying gel bait and granular bait in basement and crawl space areas; treating floor drain traps; and physically sealing the primary entry points they are using. Because they do not reproduce as rapidly or as cryptically as German roaches, the treatment timeline for American cockroach removal is generally faster. However, American roaches from active sewer systems can represent an ongoing pressure that requires periodic perimeter treatment. Our Clarksdale team evaluates which species is present during inspection and tailors the treatment accordingly. Call (323) 880-1224."
  },
  {
    q: "What is the hardest bug to squish?",
    a: "Insects vary dramatically in their structural resilience, and some are remarkably resistant to physical crushing. Among common household pests, cockroaches are among the most physically durable — their flexible exoskeleton can compress to approximately 40-60% of its original height without rupturing, allowing them to survive being stepped on if the pressure was not sufficient to fully crush the cuticle. Their distributed nervous system means that even serious injury does not cause the rapid neurological shutdown that larger animals experience. However, in terms of the insects that are truly hardest to squish, some wood-boring beetles and large scarab beetles (due to their heavily reinforced thorax) arguably exceed roaches in exoskeletal rigidity. Among insects encountered in homes, the Asian lady beetle and certain stink bug species have robust exoskeletons that resist casual crushing. None of this is practically relevant to pest control — squishing individual insects is never an effective strategy for managing a cockroach infestation in your Clarksdale home regardless of how hard or easy they are to kill individually. Professional treatment targeting the entire population is the only effective approach. Call (323) 880-1224."
  },
  {
    q: "Why should you never squish a roach?",
    a: "Beyond the egg-release and pheromone concerns mentioned earlier, there are additional compelling reasons to avoid squishing roaches as a response to an infestation. Cockroach bodies and their feces are classified as potent allergens by the American College of Allergy, Asthma and Immunology. Crushing a roach releases its bodily fluids, internal bacteria, and allergen-laden body parts into the immediate environment. These particles can become airborne and be inhaled, potentially triggering asthma attacks in sensitive household members — a particularly concerning issue for children, elderly individuals, and anyone with respiratory conditions. The crushed body and secretions also attract other cockroaches and various scavenging insects to the same spot. From a purely strategic standpoint, squishing roaches is counterproductive to professional treatment: gel bait relies on cockroaches consuming the bait and returning to the colony to share it — actively killing cockroaches by hand reduces the population of potential bait-carriers and can slow treatment effectiveness. When a professional treatment is underway, homeowners are specifically advised not to kill roaches by hand — let the bait do the work. Contact our Clarksdale team at (323) 880-1224 for a bait-forward treatment plan."
  },
  {
    q: "What bug has killed the most humans?",
    a: "Without question, the mosquito is the most lethal insect in human history — responsible for more human deaths than any other animal on Earth through the transmission of diseases including malaria, dengue fever, yellow fever, Zika virus, West Nile virus, and encephalitis. The World Health Organization estimates that mosquito-borne diseases kill between 725,000 and 1 million people annually worldwide, with malaria alone accounting for over 600,000 deaths per year, primarily in sub-Saharan Africa. The tsetse fly (Glossina species), which transmits African sleeping sickness (trypanosomiasis), has also caused enormous historical mortality. Fleas are responsible for the bubonic plague — the Black Death — which killed an estimated 30 to 50 million people in medieval Europe. In this context, cockroaches do not kill humans directly, but they do contribute to significant public health burdens through allergen-related asthma attacks, food contamination with Salmonella and E. coli, and the spread of other bacterial infections. For Mississippi residents, cockroach infestations represent a real, ongoing health risk that justifies professional treatment. Protect your Clarksdale household — call (323) 880-1224 for rapid cockroach elimination."
  },
  {
    q: "What are the worst roaches to have in your house?",
    a: "Among the cockroach species that commonly infest homes in the southern United States, German cockroaches (Blattella germanica) are universally considered the worst to have indoors. They are exclusively indoor insects that reproduce with unprecedented speed, are the most insecticide-resistant species, are the smallest (making them hardest to detect and eliminate from crevices), and are responsible for the vast majority of severe household infestations. The German cockroach is the species most commonly responsible for the massive kitchen and bathroom infestations seen in photos and videos of severe roach problems. Following German roaches in severity, the smokey-brown cockroach (Periplaneta fuliginosa) is particularly problematic in Mississippi and throughout the Gulf South — they are large outdoor-originating roaches that readily establish indoor colonies in warm, humid environments like Clarksdale's. The American cockroach, while large and alarming in appearance, is generally easier to control as outlined above. The brown-banded cockroach is notable for being the species most likely to spread beyond kitchens into bedrooms and living areas, making it particularly difficult to contain. Our Clarksdale specialists identify the exact species during inspection. Call (323) 880-1224."
  },
  {
    q: "Why do roaches run towards you?",
    a: "Cockroaches running toward a person when disturbed can seem alarming but is almost never an intentional act. The behavior is driven by several unrelated biological factors. Cockroaches have directional sensory hair cells that detect air currents — when you approach quickly, the air displacement they detect may point in the direction you are coming from, causing them to run 'toward' you as they flee the air disturbance source rather than your physical body. Additionally, cockroaches are photophobic — when suddenly exposed to light (such as turning on a room light), they instinctively run toward the nearest shadow or dark area, which may happen to be in the direction you are standing. They do not distinguish between 'toward a human' and 'toward darkness.' Cockroaches are prey animals with no predatory interest in humans — they do not bite, attack, or pursue humans intentionally. They are running from light, air disturbance, and vibration, not toward people. The instinctive reaction of startled humans to a roach running at them often amplifies the psychological impact of infestations, which is one of many reasons resolving infestations quickly improves quality of life dramatically. Call (323) 880-1224 for same-day Clarksdale cockroach treatment."
  },
  {
    q: "Why are roaches considered dirty?",
    a: "Cockroaches have earned their reputation for uncleanliness through their biology and behavior, not merely from cultural association. They feed preferentially on decaying organic matter, sewage, garbage, and rotting food — and they carry the bacteria from these sources directly into food preparation areas on their bodies and legs. Studies have confirmed that cockroaches harbor and transmit over 30 species of bacteria, including Salmonella typhimurium, Staphylococcus aureus, Streptococcus, E. coli, and Pseudomonas aeruginosa — all capable of causing serious illness in humans. Their fecal matter is deposited constantly and indiscriminately on food contact surfaces, inside food packaging, and in areas where food is prepared. Cockroaches also return to sewage systems, floor drains, and garbage regularly and then walk across kitchen counters — transferring pathogens with each crossing. Beyond bacterial transmission, their shed exoskeletons and dried feces contain potent allergen proteins (Bla g1, Bla g2, and others) that are stable in indoor environments and directly trigger asthma and allergic reactions. In summary, cockroaches are genuinely dangerous to household hygiene and food safety in Clarksdale, MS homes — their reputation for dirtiness is entirely earned. Call (323) 880-1224."
  },
  {
    q: "Which poison is called a silent killer?",
    a: "In general usage, 'silent killer' is most commonly used for carbon monoxide (CO) — a colorless, odorless gas produced by incomplete combustion of fuels in appliances, furnaces, fireplaces, and vehicles. Carbon monoxide is invisible and undetectable without a CO detector, and its initial symptoms (headache, dizziness, fatigue) often mimic the flu, meaning victims may not recognize the source of their illness before losing consciousness. From a public health standpoint, carbon monoxide detectors are essential safety devices in every home. In the context of pest control, certain pesticides applied incorrectly indoors — particularly organophosphate compounds in enclosed spaces — can act as silent killers due to their ability to cause severe neurological effects without visible warning. This is a strong argument for using only licensed, EPA-registered pest control professionals who apply products at safe concentrations in appropriate locations. Modern cockroach control primarily relies on low-toxicity gel bait formulations and targeted residual products rather than broadcast chemical sprays, minimizing exposure risk for household members. If you are concerned about the safety of pest control products used in your Clarksdale home, our team provides full transparency about all products applied. Call (323) 880-1224."
  },
  {
    q: "How do I detoxify my house?",
    a: "Detoxifying a home in the context of pest control and household health involves reducing ongoing chemical and biological exposures. Key steps include: deep cleaning to remove accumulated cockroach allergens — vacuuming with a HEPA filter, washing all surfaces including cabinet interiors with hot water and cleaning solution, laundering all soft furnishings, and cleaning HVAC filters which can redistribute allergens throughout the home. Improving ventilation reduces the concentration of both allergens and any volatile chemical compounds. Addressing moisture issues — fixing leaking pipes, installing exhaust fans in bathrooms, and reducing humidity — eliminates conditions that support cockroach and mold growth simultaneously. Sealing entry points prevents ongoing roach introduction. Replacing conventional cleaning products with unscented or low-VOC alternatives reduces chemical load. After professional pest treatment, following your technician's aeration and re-entry instructions ensures any applied products have dissipated appropriately. Encasing mattresses and pillows in allergen-impermeable covers reduces exposure to dust mite and cockroach allergens during sleep. For Clarksdale, MS homeowners dealing with active cockroach infestations, eliminating the infestation itself is the most impactful single step in reducing the allergen burden in your home. Call (323) 880-1224."
  },
  {
    q: "How do I tell if my house is making me sick?",
    a: "A home can contribute to illness in several ways, many of which are directly relevant to cockroach infestations. Symptoms that may indicate your Clarksdale home is contributing to health problems include: persistent or worsening respiratory symptoms including coughing, wheezing, shortness of breath, and frequent asthma attacks — strongly associated with cockroach and dust mite allergens in infested homes; unexplained recurring gastrointestinal symptoms including nausea, vomiting, and diarrhea — may indicate food contamination by cockroach-transported bacteria like Salmonella; increased frequency of skin rashes or hives — can indicate allergen sensitization from cockroach proteins; symptoms that improve significantly when you are away from the home for extended periods (holidays, travel) and return when you come back — a classic pattern of indoor environmental illness. Beyond cockroaches, mold exposure (particularly relevant in Mississippi's humid climate), carbon monoxide leaks, radon, lead paint dust in older homes, and VOCs from new flooring or furniture are other common indoor environmental health hazards. If you suspect your home is making you sick, addressing pest infestations — particularly cockroaches — is one of the highest-impact first steps. Call (323) 880-1224 for a Clarksdale cockroach inspection today."
  }
];

const CockroachInfo = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const half = Math.ceil(faqs.length / 2);
  const firstHalf = faqs.slice(0, half);
  const secondHalf = faqs.slice(half);

  const FaqItem = ({ item, index }: { item: typeof faqs[0]; index: number }) => (
    <div className="border border-slate-200 rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-shadow">
      <button
        className="w-full flex items-center justify-between p-6 text-left bg-white hover:bg-slate-50 transition-colors gap-4"
        onClick={() => setOpenIndex(openIndex === index ? null : index)}
      >
        <h3 className="font-bold text-slate-800 text-base leading-snug m-0">{item.q}</h3>
        {openIndex === index ? (
          <ChevronUp className="w-5 h-5 text-amber-600 shrink-0" />
        ) : (
          <ChevronDown className="w-5 h-5 text-slate-400 shrink-0" />
        )}
      </button>
      {openIndex === index && (
        <div className="px-6 pb-6 bg-white border-t border-slate-200">
          <p className="text-slate-700 leading-relaxed text-sm pt-4 font-medium">{item.a}</p>
        </div>
      )}
    </div>
  );

  return (
    <section id="faq" className="py-24 bg-gradient-to-b from-slate-950 to-slate-900 relative overflow-hidden">
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,rgba(217,119,6,0.08),transparent_60%)]" />
      <div className="container mx-auto px-4 relative z-10">
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-amber-500/10 border border-amber-500/20 text-amber-400 mb-6 font-bold uppercase tracking-widest text-xs">
            Expert Q&A
          </div>
          <h2 className="text-4xl md:text-6xl font-heading font-bold text-white mb-6 uppercase tracking-tighter">
            Knowledge <span className="text-amber-500">Base</span>
          </h2>
          <p className="text-slate-400 text-xl max-w-3xl mx-auto font-medium italic">
            Everything you need to know about cockroach extermination in Clarksdale, MS — answered by our licensed pest control specialists.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8 mb-16">
          <div className="space-y-4">
            <h3 className="text-amber-400 font-bold uppercase tracking-widest text-sm mb-6 border-b border-amber-500/20 pb-4">Part 1 — Costs, Identification & Common Questions</h3>
            {firstHalf.map((item, i) => (
              <FaqItem key={i} item={item} index={i} />
            ))}
          </div>
          <div className="space-y-4">
            <h3 className="text-amber-400 font-bold uppercase tracking-widest text-sm mb-6 border-b border-amber-500/20 pb-4">Part 2 — Biology, Treatment & Prevention</h3>
            {secondHalf.map((item, i) => (
              <FaqItem key={i + half} item={item} index={i + half} />
            ))}
          </div>
        </div>

        <div className="text-center p-10 bg-amber-600/10 border border-amber-500/20 rounded-[2rem]">
          <h3 className="text-2xl font-bold text-white mb-4 uppercase tracking-tight">Ready to End Your Roach Problem?</h3>
          <p className="text-slate-400 mb-6 font-medium italic">Our Clarksdale MS cockroach elimination specialists are available 24/7. Call now for rapid dispatch.</p>
          <a href="tel:3238801224" className="inline-flex items-center gap-3 bg-amber-600 hover:bg-amber-700 text-white font-bold px-10 py-4 rounded-2xl text-xl transition-all hover:scale-105 shadow-xl shadow-amber-900/30 uppercase tracking-widest">
            (323) 880-1224
          </a>
        </div>
      </div>
    </section>
  );
};

export default CockroachInfo;
